/**
 * Four modes, one per production route: `day-weekday` (`generate.ts`, which
 * always passes `planDate`), `day-themed` (`week/day.ts`), `week`
 * (`week/outline.ts`) and `activity` (`refine.ts`). Coverage counts per
 * configuration, not per prompt (S-03 implementation review). The context-free
 * `day` baseline was dropped on 2026-10-01 (`content-safety-gate-resume`): no
 * route sends it, so grading it paid for a configuration no teacher can reach.
 */
export const GATE_MODES = ["day-weekday", "day-themed", "week", "activity"] as const;
export type GateMode = (typeof GATE_MODES)[number];

/**
 * Which modes a prompt file feeds. `day-themed` sits under both day and week
 * prompts: its day is generated by `day-plan.pl.md` from a theme that
 * `week-outline.pl.md` wrote.
 */
const PROMPT_MODES: readonly { readonly pattern: RegExp; readonly modes: readonly GateMode[] }[] = [
  { pattern: /^src\/lib\/services\/prompts\/day-plan\.(pl\.md|schema\.json)$/, modes: ["day-weekday", "day-themed"] },
  { pattern: /^src\/lib\/services\/prompts\/week-outline\.(pl\.md|schema\.json)$/, modes: ["week", "day-themed"] },
  { pattern: /^src\/lib\/services\/prompts\/refine-activity\.(pl\.md|schema\.json)$/, modes: ["activity"] },
];

/**
 * Everything else that changes what the gate grades or how - the same set as
 * the path filter in `ci.yml`, minus the three prompts above. Any one of these
 * means the full matrix: a new judge, rubric, model, fixture or retry policy
 * is not scoped to a mode. An unknown prompt file under `prompts/` lands here
 * too, rather than being silently skipped.
 */
const FULL_MATRIX =
  /^src\/lib\/services\/prompts\/.*\.(pl\.md|schema\.json)$|^src\/lib\/services\/allowed-models\.ts$|^src\/lib\/services\/content-safety|^src\/lib\/services\/__fixtures__\/content-safety\.ts$|^src\/lib\/services\/gate-|^vitest\.gate\.config\.ts$/;

export interface GateScope {
  readonly modes: readonly GateMode[];
  readonly full: boolean;
}

/**
 * The modes a run has to cover, given the files a PR changed.
 *
 * `null` - no list, the local default - is the full matrix. So is a list with
 * nothing gate-relevant in it: CI only runs the gate when its filter matched,
 * so an empty scope here would mean the two filters disagree, and the safe
 * answer to that is to grade everything. Every allowed model is in every scope;
 * only modes narrow (`lessons.md` §3).
 */
export function gateScopeFor(changedFiles: readonly string[] | null): GateScope {
  const all: GateScope = { modes: GATE_MODES, full: true };
  if (changedFiles === null) {
    return all;
  }

  const modes = new Set<GateMode>();
  for (const file of changedFiles) {
    const prompt = PROMPT_MODES.find(({ pattern }) => pattern.test(file));
    if (prompt) {
      prompt.modes.forEach((mode) => modes.add(mode));
    } else if (FULL_MATRIX.test(file)) {
      return all;
    }
  }

  if (modes.size === 0 || modes.size === GATE_MODES.length) {
    return all;
  }
  return { modes: GATE_MODES.filter((mode) => modes.has(mode)), full: false };
}

/** `GATE_CHANGED_FILES` as CI sets it: one path per line. Unset or blank is `null`. */
export function parseChangedFiles(raw: string | undefined): string[] | null {
  const files = (raw ?? "")
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0);
  return files.length === 0 ? null : files;
}
